arrowParens: always
bracketSpacing: true
endOfLine: auto
bracketSameLine: true
printWidth: 120
proseWrap: preserve
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
jsxSingleQuote: true
