version: "3.7"

services:
  reclamation:
    image: reclamation:latest
    volumes:
      - "./logs:/server/logs"
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
    command: node app.js
