version: "3.7"

services:
  reclamation:
    image: ghcr.io/monday-morning/project-reclamation:production
    volumes:
      - "./server/env:/server/env:rw"
      - "./server/logs:/server/logs:rw"
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
    command: node app.js
