module.exports = {
  apps: [
    {
      name: 'MM API Server',
      script: './app.js',
      watch: false,
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
        SESSION_SECRET: 'your-secret-session-key',
        SESSION_KEY: 'your-secret-session-key-value',
        MONGO_SESSION_URL: 'your-mongodb-auth-url-for-session-data',
        MONGO_APP_URL: 'your-mongodb-auth-url-for-app-data',
        FIREBASE_PROJECT_ID: 'your-firebase-project-id',
        FIREBASE_KEY_ID: 'your-firebase-project-id',
        FIREBASE_PRIVATE_KEY: 'your-firebase-project-id',
        FIREBASE_CLIENT_ID: 'your-firebase-project-id',
        FIREBASE_AUTH_URI: 'your-firebase-project-id',
        FIREBASE_TOKEN_URI: 'your-firebase-project-id',
        FIREBASE_AUTH_PROVIDER_CERT_URL: 'your-firebase-project-id',
        FIREBASE_CLIENT_CERT_URL: 'your-firebase-project-id',
        GCP_STORAGE_BUCKET: 'your-gcp-storage-bucket',
        TEST_AUTH_KEY: 'some-sample-jwt-token',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 80,
        SESSION_SECRET: 'your-secret-session-key',
        SESSION_KEY: 'your-secret-session-key-value',
        MONGO_SESSION_URL: 'your-mongodb-auth-url-for-session-data',
        MONGO_APP_URL: 'your-mongodb-auth-url-for-app-data',
        FIREBASE_PROJECT_ID: 'your-firebase-project-id',
        FIREBASE_KEY_ID: 'your-firebase-project-id',
        FIREBASE_PRIVATE_KEY: 'your-firebase-project-id',
        FIREBASE_CLIENT_ID: 'your-firebase-project-id',
        FIREBASE_AUTH_URI: 'your-firebase-project-id',
        FIREBASE_TOKEN_URI: 'your-firebase-project-id',
        FIREBASE_AUTH_PROVIDER_CERT_URL: 'your-firebase-project-id',
        FIREBASE_CLIENT_CERT_URL: 'your-firebase-project-id',
        GCP_STORAGE_BUCKET: 'your-gcp-storage-bucket',
        TEST_AUTH_KEY: 'some-sample-jwt-token',
      },
    },
  ],
};
