name: Development Server Deploy

on:
  push:
    branches: [development]

jobs:
  devDeploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run PM2 Deploy
        run: cd server && npx pm2 deploy staging
