name: Unit Tests

on:
  workflow_call:
    inputs:
      package_path:
        required: true
        type: string

jobs:
  mocha:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Use Actions Dev Cache
        uses: actions/cache@v2
        id: yarn-dev-cache
        if: ${{ inputs.setup_dev }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-dev-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dev Dependencies
        if: ${{ inputs.setup_dev }} && steps.yarn-dev-cache.outputs.cache-hit != 'true'
        run: yarn install && cd server && yarn install
          
      - name: Install Mocha
        run: yarn global add mocha

      - name: Run Mocha
        id: mocha_run
        run: mocha --package ${{ inputs.package_path }} --check-leaks --reporter spec --recursive --exit
